version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 238027390572.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t api-marketplace-backend .
      - docker tag api-marketplace-backend:latest 238027390572.dkr.ecr.ap-south-1.amazonaws.com/api-marketplace-backend:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 238027390572.dkr.ecr.ap-south-1.amazonaws.com/api-marketplace-backend:latest
      - echo Writing image definitions file...
      - printf '[{"name":"app","imageUri":"%s"}]' 238027390572.dkr.ecr.ap-south-1.amazonaws.com/api-marketplace-backend:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json